import { ERROR_TEMPLATE_EMPTY_OR_NULL, ERROR_TEMPLATE_MAX_LENGTH, ERROR_TEMPLATE_NOT_AVAILABLE } from "./error-templates.constants";
import { PROPERTY_NAME } from "./properties.constants";

export const BRAND='brand';
export const BRAND_NAME='brand name';
export const BRAND_DESCRIPTION='brand description';
export const BRAND_NAME_MAX_LENGTH=50;
export const BRAND_DESCRIPTION_MAX_LENGTH=120;

export const BRAND_NAME_MAX_LENGTH_ERROR=ERROR_TEMPLATE_MAX_LENGTH(BRAND_NAME,BRAND_NAME_MAX_LENGTH);
export const BRAND_DESCRIPTION_MAX_MAX_LENGTH_ERROR=ERROR_TEMPLATE_MAX_LENGTH(BRAND_DESCRIPTION,BRAND_DESCRIPTION_MAX_LENGTH);

export const BRAND_NAME_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(BRAND_NAME);
export const BRAND_DESCRIPTION_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(BRAND_DESCRIPTION);

export const BRAND_NAME_NOT_AVAILABLE_ERROR=ERROR_TEMPLATE_NOT_AVAILABLE(PROPERTY_NAME, BRAND);

export const BRAND_TITTLE_ERROR='Brand Creation Failed';
export const BRAND_TITTLE_SUCCESSFULLY='Brand Created Successfully';



