import { ERROR_TEMPLATE_EMPTY_OR_NULL, ERROR_TEMPLATE_MAX_LENGTH, ERROR_TEMPLATE_NOT_AVAILABLE } from "./error-templates.constants";
import { PROPERTY_NAME } from "./properties.constants";

export const CATEGORY='category';
export const CATEGORY_NAME='category name';
export const CATEGORY_DESCRIPTION='category description';
export const CATEGORY_LIST='category list';
export const CATEGORY_NAME_MAX_LENGTH=50;
export const CATEGORY_DESCRIPTION_MAX_LENGTH=90;

export const CATEGORY_NAME_MAX_LENGTH_ERROR=ERROR_TEMPLATE_MAX_LENGTH(CATEGORY_NAME,CATEGORY_NAME_MAX_LENGTH);
export const CATEGORY_DESCRIPTION_MAX_MAX_LENGTH_ERROR=ERROR_TEMPLATE_MAX_LENGTH(CATEGORY_DESCRIPTION,CATEGORY_DESCRIPTION_MAX_LENGTH);

export const CATEGORY_NAME_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(CATEGORY_NAME);
export const CATEGORY_DESCRIPTION_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(CATEGORY_DESCRIPTION);

export const CATEGORY_NAME_NOT_AVAILABLE_ERROR=ERROR_TEMPLATE_NOT_AVAILABLE(PROPERTY_NAME, CATEGORY);

export const CATEGORY_TITTLE_ERROR='Category Creation Failed';
export const CATEGORY_TITTLE_SUCCESSFULLY='Category Created Successfully';