import { BRAND } from "./brand.constants";
import { CATEGORY_LIST } from "./category.constants";
import { ERROR_TEMPLATE_EMPTY_OR_NULL, ERROR_TEMPLATE_GREATER_THAN, ERROR_TEMPLATE_NOT_AVAILABLE, ERROR_TEMPLATE_REQUIRED } from "./error-templates.constants";
import { PROPERTY_AMOUNT, PROPERTY_NAME, PROPERTY_PRICE } from "./properties.constants";

export const PRODUCT='product';
export const PRODUCT_URL='/panel/product';
export const PRODUCT_NAME='product name';
export const PRODUCT_MIN_PRICE=1;
export const PRODUCT_MIN_AMOUNT=1;
export const PRODUCT_DESCRIPTION='product description';

export const PRODUCT_NAME_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(PRODUCT_NAME);
export const PRODUCT_NAME_NOT_AVAILABLE_ERROR=ERROR_TEMPLATE_NOT_AVAILABLE(PROPERTY_NAME, PRODUCT);
export const PRODUCT_DESCRIPTION_EMPTY_OR_NULL_ERROR=ERROR_TEMPLATE_EMPTY_OR_NULL(PRODUCT_DESCRIPTION);

export const PRODUCT_AMOUNT_REQUIRED_ERROR=ERROR_TEMPLATE_REQUIRED(PROPERTY_AMOUNT);
export const PRODUCT_AMOUNT_NOT_INTEGER_ERROR='The amount must be an integer number.';
export const PRODUCT_AMOUNT_GREATER_THAN_ERROR=ERROR_TEMPLATE_GREATER_THAN(PROPERTY_AMOUNT,PRODUCT_MIN_AMOUNT);

export const PRODUCT_PRICE_REQUIRED_ERROR=ERROR_TEMPLATE_REQUIRED(PROPERTY_PRICE);
export const PRODUCT_PRICE_GREATER_THAN_ERROR=ERROR_TEMPLATE_GREATER_THAN(PROPERTY_PRICE,PRODUCT_MIN_PRICE);

export const PRODUCT_BRAND_REQUIRED_ERROR=ERROR_TEMPLATE_REQUIRED(BRAND);

export const PRODUCT_CATEGORY_LIST_REQUIRED_ERROR=ERROR_TEMPLATE_REQUIRED(CATEGORY_LIST);
export const PRODUCT_CATEGORY_LIST_MAX_LENGTH_ERROR='The category list cannot exceed 3 items.';


export const PRODUCT_TITTLE_ERROR='Product Creation Failed';
export const PRODUCT_TITTLE_SUCCESSFULLY='Product Created Successfully';